### PR TITLE
NIFI-5226: Implement a Record API based PutInfluxDB processor

### PR DESCRIPTION
**Pull request by bednar**
Thank you for submitting a contribution to Apache NiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with NIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under nifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under nifi-assembly?
- [x] If adding new Properties, have you added .displayName in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by bednar** [comment]
The full suite of tests is passing:

passing-test

**Comment by bednar** [comment]
Post 50000 measurements in 50 threads:

```
seq 50000 | xargs -P 50 -I INDEX curl -i -XPOST "http://localhost:8668/contentListener" --data-binary 'weather,location=us-midwest temperature=INDEX INDEX'
```

**Comment by rhajek** [comment]
In the case org.influxdb.InfluxDBIOException: java.net.SocketTimeoutException: timeout

Exception message is not shown in NiFi console.

getLogger().error(INFLUX_DB_ERROR_MESSAGE, new Object[]{flowFileName, e.getLocalizedMessage()}, e);

image

**Review by ivankudibal — APPROVED** [review]

**Review by rhajek — APPROVED** [review]

**Comment by bednar** [comment]
Post 100000 measurements grouped in 1000 bulk and used 50 threads:

```
#!/bin/bash

fileCount=100
measurementInFileCount=1000

for ((i=1; i<=fileCount; i++))
do
   echo "Generating lineprotocol.$i file..."
   seqstart=`expr $measurementInFileCount \* $i`
   seqend=`expr $measurementInFileCount \+ $seqstart - 1`
   seq -f "%.0f" $seqstart $seqend | xargs -P 100 -I INDEX printf 'weather,location=us-midwest temperature=INDEX INDEX\n' > lineprotocol.$i
done

echo "Pushing data to Apache NiFi..."
seq $fileCount | xargs -P 50 -I INDEX curl -i -XPOST "http://localhost:8668/contentListener" --data-binary @lineprotocol.INDEX

echo "Removing generated files..."
seq $fileCount | xargs -I INDEX rm lineprotocol.INDEX

echo
echo "Total count of the measurements: " $(($measurementInFileCount * $fileCount))
```

**Comment by bednar** [comment]
Created pull request in Apache NiFi repository: [NIFI-5226: Implement a Record API based PutInfluxDB processor](https://github.com/apache/nifi/pull/2743/)

**Pull request merged**
